name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: sudo apt install libglew-dev libglfw3-dev libfreetype-dev libassimp-dev
    - name: mkdir_build
      run: mkdir build && cd build
    - name: cmake_project
      run: cmake ..
    - name: make_project
      run: make -j4
